### ISSUE TITLE
Check notebook runs in Binder

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#11]
Hey @milanwilliams  - can you please follow [this link to the SLTimer README](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/README.md) and click on the "Launch Binder" button? That should bring up a Jupyter notebook view of the repository, from where you should be able to click through to your Demo notebook and execute it: can you try this please, and report back on any errors? The idea is to enable anyone on the web to run your notebook and reproduce the notebook's outputs in a live demo.

**Comment by milanwilliams** [comment]
Hello @drphilmarshall 

I received one error message, but I believe it is harmless. It popped up after running the script: %matplotlib inline. Here is the error message: 

/home/main/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Other than that, there were no other problems!

**Comment by drphilmarshall** [comment]
Great - I got the same thing, it's just a warning. Thanks!

On Mon, Jun 13, 2016 at 1:50 PM, Milan M. Williams <notifications@github.com
