### ISSUE TITLE
Start sphinx documentation

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#15]
We'll be getting to work on the `SLTimer` code itself very soon, and will be documenting it as we go. @heather999 would you mind setting up the _simplest possible sphinx system_ (with very brief instructions for building and deploying it) so that @milanwilliams and I can add to it, please? This would be a great help, since I am relatively new to sphinx. We can make a simple `gh-pages` branch to display the html for now, and move to LSST the docs later if necessary or desired. What do you think? As you can see, our current code is _extremely simple_ so now's a good time to build the minimal starter kit. Thank you! :-)

**Comment by drphilmarshall** [comment]
I decided to take a quick look at readthedocs myself, to see how it works. There's no `index.rst` or `api.rst` yet, but we are on the web at least: http://sltimer.readthedocs.io/

**Comment by drphilmarshall** [comment]
See PR #47 for more discussion - this issue should get closed by a commit, when that PR is merged.

**Comment by heather999** [comment]
Taking a peek - thanks @drphilmarshall !
