### ISSUE TITLE
Fix PyCS problems with tutorial

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#16]
We need to ask the `PyCS` dev team for help with our [tutorial](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/PyCS_Tutorial.ipynb). I'll contact them!

**Comment by mtewes** [comment]
... and to avoid those `nan` uncertainty estimates related to the empty true time-delay bins (given the 4 mock curves of the simulation), you could use one single bin (down in Section 5.3), that is specifying **nbins=1** in

```
pycs.sim.plot.measvstrue(simresults, errorrange=3.5, r=5.0, nbins=1, binclip=True, binclipr=20.0,
        plotpoints=False, filename="fig_measvstrue.pdf", dataout=True)
```

In this case, the error computation (quadratic sum of maximum bias and variance) is equivalent to the Root Mean Square Error (RMSE) of the estimates from the mock curves.
When the extrinsic variability is gentle and the delays are small compared to the season length (i.e., the bias is negligible or at least does not depend on the true delay), this RMSE is perfectly fine, and there is no need to draw hundreds of mock curves just to fill those bins. Here is how it looks with just 4 mocks (from your notebook):
![unknown](https://cloud.githubusercontent.com/assets/1928653/16303269/1a476464-3950-11e6-8d2d-f724e234a0e9.png)

**Comment by drphilmarshall** [comment]
Great, thanks very much @mtewes :-) I also saw that you replied to our issues at https://github.com/COSMOGRAIL/PyCS/issues/11 and https://github.com/COSMOGRAIL/PyCS/issues/12 - thank you!

@milanwilliams can you please make the changes Malte suggests and see if you can reproduce his results? Thanks!

**Comment by drphilmarshall** [comment]
Oops - I still see "nan"s! Re-opening and fixing...
