### ISSUE TITLE
Pipe PyCS output into plain text logfile?

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#20]
I'm not sure how to capture a stdout/stderr stream in a logfile from python, maybe @jchiang87 can advise? The library functions we call do a lot of printing:is there a way to quietly hide that output in a file without changing the library code?

**Comment by jchiang87** [comment]
It looks like you would need something like this:
http://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/

**Comment by drphilmarshall** [comment]
Interesting! With a small tweak we are almost literate

``` python
from contextlib import redirect_stdout as output_redirected_to

we = SLTimer()
a_logfile = io.StringIO()

with output_redirected_to(a_logfile): we.estimate_time_delays()
```

;-)
