### ISSUE TITLE
Uncertainty estimation options

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#23]
The number of copies `Ncopies` and the number of synthetic datasets `Nmocks` both need to be kwargs of an `estimate_uncertainties` method (currently called "complete_error_analysis"), don't you think?

**Comment by milanwilliams** [comment]
This line is in the latest pull request `S.estimate_uncertainties(n=1,npkl=4)`. #26 should close this issue.
