### ISSUE TITLE
Example TDC2 Analysis

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#27]
This is an epic. We need a new notebook, showing SLTimer analysis of the [example TDC2 gateway data](http://www.slac.stanford.edu/~pjm/LSST/DESC/SLTimeDelayChallenge/release/tdc2/gateway/tdc2-gateway-example.txt). The download method should be good, but we'll need a new read method, that can understand the TDC2 data format and create `lcs` objects . We can ignore the filter column at first, but soon we'll want to take it into account and make whitened light curves. Have fun, @milanwilliams ! :-)
- [x] #36 Turn TDC2 Notebook into Example Analysis 
- [x] #37 Issues Need Milestones 

Postponed for later:
- #33 Extract and write out "samples" from "joint posterior PDF" for time delays

**Comment by milanwilliams** [comment]
* [ ] #33
* [ ] #36 
* [ ] #37

**Comment by mtewes** [comment]
A bit late and not sure if helpful, but to get inspiration about how to use PyCS to read a nanomaggie table, here is how we did for TDC1:
https://github.com/COSMOGRAIL/PyCS/blob/master/pycs/tdc/util.py#L109

It might be possible to adapt this for TDC2, using the lc.flexibleimport options
startline, and propertycols to read the band, but it might also be simpler just to rewrite an import function from scratch.

**Comment by drphilmarshall** [comment]
@mtewes Oh, nice! We didn't see that. @milanwilliams wrote a nice alternative multi-filter light curve import function, [here](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/python/desc/sltimer/IO.py#L148), trying to keep close to the `PyCS` conventions.
