### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#3]
@jchiang87

Here's another WG code repo that could use some guidance regarding structuring, as in https://github.com/DarkEnergyScienceCollaboration/Monitor/issues/2 . Would you mind showing us the way in your fork, please? I guess we'd like to be able to write things like

```
import desc.sltimer
We = desc.sltimer.SLTimer()
```

I don't know yet if we'll want to collect SL code together in `desc.sl` or if the `SLTimer` will become part of a "cosmology library" but both those things are possible - at first I think `desc.sltimer` would set a reasonable example. Thanks!

**Comment by drphilmarshall** [comment]
PS. The next lines I have in mind are 

```
We.read_in_catalog(from=filename)
We.estimate_time_delay()
```

;-)

**Comment by jchiang87** [comment]
@drphilmarshall Can you grant me access rights to this repo?  Thanks!

**Comment by drphilmarshall** [comment]
Done! Is read/fork access not enough for this kind of support?

**Comment by jchiang87** [comment]
I've been branching off master (a la DM) rather than doing a fork.  I could fork if you prefer.

**Comment by jchiang87** [comment]
Changes pushed at f70bc06d

**Comment by drphilmarshall** [comment]
Thanks!
