### ISSUE TITLE
Turn TDC2 Notebook into Example Analysis

### ISSUE THREAD

**Issue by milanwilliams** [DarkEnergyScienceCollaboration/SLTimer#36]
Is there a significant difference between the whitened and unwhitened light curves? (given the uncertainties, this means we have to estimate uncertainties correctly #33) 

Also, do we get the right answer? (@drphilmarshall can you please get the time delays from Kai? Thanks! See also #38)

We will also rename the notebook, and add in sections for the analysis of whitened and unwhitened data, and compare with an overlaid corner plot.

**Comment by drphilmarshall** [comment]
For an example of an "overlaid corner plot" see [this notebook](https://github.com/tommasotreu/AARV/blob/master/attic/spare-or-old-figures/DdtDa.ipynb). You can get the corner package with `pip install corner` - so it'll need to be added to our `requirements.txt` file too.

**Comment by drphilmarshall** [comment]
We now have a [notebook with time delay estimates from both unwhitened and whitened TDC2 example data](https://github.com/DarkEnergyScienceCollaboration/SLTimer/blob/master/notebooks/SLTimer_TDC2_Example.ipynb), via #34. Next thing to do is extract the posterior samples, and upgrade the estimated delays into an overlaid corner plot ( #33 )
