### ISSUE TITLE
Issues Need Milestones

### ISSUE THREAD

**Issue by milanwilliams** [DarkEnergyScienceCollaboration/SLTimer#37]
@drphilmarshall can you please give me write access so that I can put a deadline on the issues that I need to finish? Thank you!

**Comment by drphilmarshall** [comment]
Done! You should be able to create milestones, assign issues etc now.

**Comment by drphilmarshall** [comment]
Thanks for the milestones, @milanwilliams ! I moved the two outstanding issues to the TDC2 launch milestone, so yours is nice and complete. Thanks for all your help this summer! It was a real pleasure having you with us :-)
