### ISSUE TITLE
More TDC2 Data

### ISSUE THREAD

**Issue by milanwilliams** [DarkEnergyScienceCollaboration/SLTimer#38]
@drphilmarshall Can you ask Kai for the complete tdc-gateway data set and also the true time delays, please? Thank you!

**Comment by drphilmarshall** [comment]
Done, in [this issue comment in the private SLTimeDelayChallenge repo](https://github.com/DarkEnergyScienceCollaboration/SLTimeDelayChallenge/issues/164#issuecomment-233200489)!
