### ISSUE TITLE
Semi-automatic initialization

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#42]
In https://github.com/DarkEnergyScienceCollaboration/SLTimer/issues/40#issuecomment-245575114 @mtewes and @vbonvin made some good suggestions for how to initialize the `pycs` models before optimizing. Let's explore these, and see if we can find a simple approach that works most of the time with TDC2-like data.

**Comment by chto** [comment]
I am going to try two things:
The  first one is to write a preliminary fit without microlensing, and then fit the microlensing, to see how this goes. 
The second one is to try to daw random time shift as a starting position and fit them.

**Comment by chto** [comment]
We've decided to do it another way. 
Here is what we do know. 
We  sample time delay parameter space by simple montecarlo method. For each point, we fit spline function (intrinsic+extrinsic) and calculate chi-square. 
We then choose initial time delay to the the one with least chi-square.
