### ISSUE TITLE
Write out sample time delays in slcosmo format

### ISSUE THREAD

**Issue by chto** [DarkEnergyScienceCollaboration/SLTimer#49]
I am going to create a function for compute_likelihood_simpleMC to save the samples and make it compatible with SLCosmo( i.e. store them in "tdc2samplefile" format).

**Comment by drphilmarshall** [comment]
Sounds good! You should issue these tasks separately, and make the issue
titles as informative as possible - you can edit the issue title any time.
Maybe make a separate issue for the r+i band only test, and then rename
this one something like "Write out sample time delays in slcosmo format"?
In general each issue should address just one issue (the exception is when
you make an issue to host a set of related issues - this is called an
"epic").

**Comment by chto** [comment]
Thanks @drphilmarshall for very useful comment. I've changed my issues to make them more concrete. But I still have a question that am I able to assign an issue to myself?

**Comment by drphilmarshall** [comment]
Good good. I just changed your repo permissions, you should be able to assign/label/milestone the issues now.
