### ISSUE TITLE
Add new issues, label/milestone/assign, report to old ones

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/SLTimer#52]
Hey @chto can you do some project mgmt this morning please? We made a short list of issues to be created on Tuesday, a photo of my whiteboard is below. Can you please make one issue for each of these to-do items, and use the comments to say what you think needs to be done, and then assign it to either yourself or me? You should also label each issue (especially if it is a sub-task of an "epic" issue), and attach each one to a milestone (TDC2 Launch, in this case, I think). You can close this when you're done. Thanks!

![image](https://cloud.githubusercontent.com/assets/710903/19974419/b0a4a4f4-a1a5-11e6-9f5a-9bbc71a281f1.png)

**Comment by chto** [comment]
@drphilmarshall I have open an issue for each items we've discussed. Please take a look. 
However, as for the labeling, can I create an epic issue and make other issue subtask of the epic one?

**Comment by drphilmarshall** [comment]
Yes! Go ahead and make any new labels you need. Don't forget to close this out when you are done! :-)
