### ISSUE TITLE
Integrate P(H_0) from 0 to inf

### ISSUE THREAD

**Issue by chto** [DarkEnergyScienceCollaboration/SLTimer#55]
In #54  we integrate P(H_0) from -inf to inf. However, we know the universe is expanding, so it's more real to integrate P(H_0) from 0 to inf.

**Comment by chto** [comment]
Derived and implemented in SLTimer prior method. 
The result looks the same as the one when we integrate H0 from -inf to inf for TDC2 gateway one data. The reason is that a and b in the formula are large, so the result degenerate to the formula derived by integrating H0 from -inf to inf. 

<img width="931" alt="sltimer_tdc2_analysis" src="https://cloud.githubusercontent.com/assets/16754618/20035569/ca0556a6-a3a7-11e6-897e-dc932de15779.png">

**Comment by drphilmarshall** [comment]
Interesting: I was expecting more of an impact. Thanks!
